Testing job

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -12,6 +12,12 @@ on:
       sigla:
         type: string
         default: SC4
+      jobsuccess:
+        type: string
+        default: sucesso
+      jobfailed:
+        type: string
+        default: falha
   repository_dispatch:
     types: [on-demand-test]
 
@@ -28,28 +34,40 @@ jobs:
       - run: echo "A"
       - id: set
         run: |
-          echo "::set-output name=run_job_b::no"
+          exit 1
+
+  should_run_success:
+    name: b
     outputs:
-      run_job_b: ${{ steps.set.outputs.run_job_b }}
+      run_job_b: ${{ steps.set_success.outputs.run_job_b || steps.set_failure.outputs.run_job_b }}
+    
+    runs-on: ubuntu-latest
+    needs:
+      - a
+    steps:
+      - run: echo "B"
+      - id: set_success
+        if: always() && needs.a.result == 'success'
+        run: |
+          JOB_FILE=`echo "${{ inputs.jobsuccess }}" | base64`
+          echo "jobfile=$JOB_FILE" >> $GITHUB_OUTPUT
+      - id: set_failure
+        if: always() && needs.a.result != 'success'
+        run: |
+          JOB_FILE=`echo "${{ inputs.jobfailed }}" | base64`
+          echo "jobfile=$JOB_FILE" >> $GITHUB_OUTPUT
+
   b:
     name: b
     runs-on: ubuntu-latest
     needs:
-      - a
-    if: needs.a.outputs.run_job_b == 'yes'
+      - should_run_success
     steps:
-      - run: echo "B"
-  c:
-    name: c
-    runs-on: ubuntu-latest
-    needs:
-      - a
-      - b
-    if: always() && 
-        needs.a.result == 'success' &&
-        (needs.b.result == 'success' || needs.b.result == 'skipped')
-    steps:
-      - run: echo "C"
+      - id: jobfile
+        run: echo "$JOB_FILE"
+    env:
+      JOB_FILE: ${{ needs.should_run_success.outputs.run_job_b }}
+
 
 #   compilation:
 #     runs-on: ubuntu-latest
